### ISSUE TITLE
Update data with travis

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/SwissHistMunData#1]
In `tic.R`:

- Run tests on Travis CI
- If successful, proceed with regular checking
- If failing, run a second time
- If failed a second time, abort
- If successful then:
    - commit
    - bump package version
    - push to GitHub
    - end processing (the next Travis run will test again)

CC @TeddyLeeJones.

**Comment by ThomasKnecht** [comment]
Do I have to run the code in the tic.R file for the tests?
I get no output when running the code.

**Comment by krlmlr** [comment]
Use `devtools::test()` (RStudio: Cmd + Shift + T or Ctrl + Shift + T).

**Comment by ThomasKnecht** [comment]
I added steps to the tic.R file. I made the changes on the master-branch. 
I used dsl_load() and dsl_get() to test the workflow. I also let the run_all_stages() to run the workflow. So far everything looks fine. I am not sure about the deployment steps. 
Should I just commit the changes in the tic.R file or send the workflow in an issue comment?

**Comment by krlmlr** [comment]
Can you please submit a PR?

**Comment by ThomasKnecht** [comment]
Ah, sorry I must have misunderstood you. I thought for changes in the tic-workflow we should work on the master?
Therefore I did not create a branch.
I commited the tic.R file now. 
We can also set back all my commits and i open a branch...

**Comment by TSchiefer** [comment]
How do we make sure that the data is updated on a regular basis using this approach? (how do we initialize Travis)

**Comment by krlmlr** [comment]
I see the tic workflow, closing for now.
