### ISSUE TITLE
Check if API-link is pointing to the newest dataset

### ISSUE THREAD

**Issue by ThomasKnecht** [krlmlr/SwissHistMunData#10]
We saw, that the link shows only the 2019 file and not the most recent municipality mutation data (2020-01-01).

**Comment by krlmlr** [comment]
Saw this too. Bummer.

zazuko maintains a linked data version of this dataset, see the link in https://github.com/krlmlr/SwissCommunes/issues/3. They also need to update the link every year: https://github.com/zazuko/fso-lod/commit/e8f08dee258697b77e9091c6f601be6675518639.

We could get the link automatically with rvest, I suspect it's easier to quickly look it up and update manually every year.

**Comment by krlmlr** [comment]
Closing in favor of https://github.com/cynkra/munch/issues/20.
