### ISSUE TITLE
Integrate SwissHistMunData in swissdata?

### ISSUE THREAD

**Issue by TSchiefer** [krlmlr/SwissHistMunData#12]
Advantages:
1. automated update infrastructure already available
1. swissdata would also benefit

TBD

**Comment by krlmlr** [comment]
Maybe for the derived mapping tables at https://cynkra.github.io/SwissCommunes/articles/data.html?

**Comment by krlmlr** [comment]
What is swissdata? Please open in munch if still relevant.
