### ISSUE TITLE
How can i Install SwissHistMunData in tic.R

### ISSUE THREAD

**Issue by ThomasKnecht** [krlmlr/SwissHistMunData#4]
@krlmlr 
In the tic.R file I use functions from the SwissHistMunData package. Therefore, the package needs to be pre-installed so that travis-ci can actually access the needed functions. 

The problem is, that in the .travis.yaml-file the following steps are made:
before_install: R -q -e 'install.packages(c("remotes", "curl")); remotes::install_github("ropenscilabs/tic"); tic::prepare_all_stages(); tic::before_install()'

The earliest I can install the SwissHistMunData is in the step: "before_install". But the package is already needed in the tic::prepare_all_stages()-step. 
Shall I change the .travis.yaml-file so that i install the SwissHistMunData package after the installation of the tic package?

**Comment by krlmlr** [comment]
Please use a pattern like:

```r
get_stage("before_build") %>%
  add_code_step({
    remotes::install_local(".")
    ...
  })
```

**Comment by ThomasKnecht** [comment]
The following error in the Travis CI log shows up:
✔ Loading tic stage configuration from tic.R
Error: Unknown stage before_build.

**Comment by ThomasKnecht** [comment]
See #5

**Comment by krlmlr** [comment]
Can you try `"before_script"` instead of `"before_build"` ?

**Comment by ThomasKnecht** [comment]
✔ Loading tic stage configuration from tic.R
Error in loadNamespace(name) : 
  there is no package called ‘SwissHistMunData’

It does not work with "befor_install" and "install" either. Same error message.

The only way I could make it work is in #5.

Could be, that I need to find another way for the whole workflow...

**Comment by krlmlr** [comment]
No longer using tic.
